### ISSUE TITLE
موتور پردازش متنِ برنامه

### ISSUE THREAD

**Issue by neesti** [kokabi1365/Vajehyar#1]
<div dir="rtl">
پیشنهاد می‌کنم حالا که برنامه متن‌باز است، برای پردازش متن از موتور GDIPP استفاده کنی که کیفیت نمایش متن را بسیار بهبود می‌دهد. 

اطلاعات بیشتر:
https://code.google.com/archive/p/gdipp

**Comment by kokabi1365** [comment]
ممنون از پیشنهادی که دادید.
برای واسط کاربری برنامه از WPF استفاده کردم که مبتنی بر DirectX هست و موتور پردازش متنش DirectWrite است. این یعنی حتی اگه بخواهیم نمیتونیم از تکست رندرهای دیگه‌ای مثل GDIPP که مبتنی بر +GDI هستند استفاده کنیم. در واقع این‌ها دو تکنولوژی جدا از هم هستند و البته WPF نسل جدیدتره که به نوعی در UWP هم شاهدش هستیم.
