### ISSUE TITLE
کمینه‌شدن پنجرهٔ برنامه در نوار وظایف ویندوز

### ISSUE THREAD

**Issue by neesti** [kokabi1365/Vajehyar#2]
<div dir=rtl>
وقتی با ماوس در فضایی غیر از پنجرهٔ برنامه کلیک می‌کنم، پنجرهٔ برنامه در سینی سیستم (System Tray) مقیم می‌شود؛ درحالی‌که قاعدتاً فقط باید در Taskbar ویندوز کمینه (Minimize) شود.

**Comment by kokabi1365** [comment]
اتفاقاً این فیچری هست که

**Comment by kokabi1365** [comment]
اتفاقاً این فیچری هست که خودم تعبیه کردم تا نیازی نباشه حین نوشتن بین برنامه و متن سوئیچ کنید. از طرفی چون کاربر به جز جستجوی واژه کار دیگه‌ای با برنامه نداره قرار گرفتن در تسکبار هم جالب نیست. با شورتکات برنامه باز میشه، جستجو می‌کنید، نتیجه رو می‌بینید و با زدن کلید ESC پنجره بسته میشه که حتی با کلیک خارج از محیط برنامه نیازی به این هم نیست. اگه واقعاً بدونم این قضیه آزاردهنده است می‌تونم به صورت اختیاری در بخش تنظیمات برنامه اضافه کنم. نظرتون چیه؟

**Comment by neesti** [comment]
<div dir=rtl>
فرمایشتان متین است. 
بهتر است این ویژگی به‌صورت یک گزاره در بخش تنظیمات برنامه اضافه شود.

**Comment by kokabi1365** [comment]
در آپدیت بعدی منتشر خواهم کرد. 
ممنون از شما.

**Comment by kokabi1365** [comment]
### header test

> test quote


#1 test

**Comment by kokabi1365** [comment]
- [1] one

**Comment by neesti** [comment]
<div dir=rtl>
قرار بود ویژگی کمینه‌شدن در سینی سیستم به‌صورت یک گزاره به تنظیمات برنامه اضافه شود؛ اما الان (نسخهٔ 1.0) فقط با فشردن دکمهٔ Escape است که پنجره در سینی سیستم جای می‌گیرد.

**Comment by kokabi1365** [comment]
چون چند نفر دیگر هم دقیقاً مشکل شما را داشتند ترجیح دادم کلاً این قابلیت را حذف کنم و صفحۀ تنظیمات را بیهوده شلوغ نکنم. با این حال اگر به بودن چنین قابلیتی احساس نیاز می‌کنید به تنظیمات اضافه کنم؟

**Comment by neesti** [comment]
<div dir=rtl>
من که شخصاً به آن نیاز دارم. ممنون می‌شوم اضافه‌اش کنید.

**Comment by kokabi1365** [comment]
<div dir="rtl">
بسیار خوب. پس در نسخۀ بعدی اضافه می‌کنم.
</div>
