### ISSUE TITLE
مسئلهٔ فونت

### ISSUE THREAD

**Issue by neesti** [kokabi1365/Vajehyar#4]
<div dir=rtl>
با اینکه فونت برنامه را در تنظیماتش تغییر دادم، فونت جعبهٔ (Box) جست‌وجو همچنان تاهوما مانده! 

ضمناً نمایش نام فونت‌ها در منوی پایین‌افتِ فونت‌ها الفبایی نیست!

**Comment by kokabi1365** [comment]
در نسخۀ بعدی برطرف می‌کنم.
البته فونت پیش‌فرض کادر جستجو و سایر قسمت‌های رابط کاربری باید IranSans باشد نه تاهوما. آیا برای شما فقط کادر جستجو تاهوماست؟

**Comment by neesti** [comment]
<div dir=rtl>
بله، فقط فونت کادر جست‌وجو تاهوما است. 

![image](https://user-images.githubusercontent.com/14938202/58454755-ad763b00-8134-11e9-812c-1226050a0338.png)
