### ISSUE TITLE
پنجرهٔ تنظیمات

### ISSUE THREAD

**Issue by neesti** [kokabi1365/Vajehyar#5]
<div dir=rtl>
وقتی روی آیکون برنامه در سینی سیستم کلیک می‌کنم تا پنجرهٔ دسترسی به تنظیماتش باز شود، با پنجره‌ای بزرگ و غیرعادی از نظر اندازه روبرو می‌شوم! 

![image](https://user-images.githubusercontent.com/14938202/58450222-3be1c100-8123-11e9-9720-22ded54071bd.png)

از ویندوز سون استفاده می‌کنم که به‌روز هم شده است.

**Comment by kokabi1365** [comment]
از چه رزولوشن استفاده می‌کنید؟
آیا این مشکل جاهای دیگه هم اتفاق می‌افته؟ 

لطفاً تصویری از صفحۀ اول هم ارسال کنید.
![Screenshot_1](https://user-images.githubusercontent.com/44271870/58454145-cc73cd80-8132-11e9-84b7-d1b4a3340d70.jpg)

**Comment by neesti** [comment]
![image](https://user-images.githubusercontent.com/14938202/58454611-4062a580-8134-11e9-9080-63d41f40ff1f.png)

**Comment by kokabi1365** [comment]
<div dir="rtl">
> خیر این مشکل در هیچ برنامهٔ دیگری پیش نمی‌آید!
مقصود بنده جای دیگری از برنامۀ واژه‌یار بود. مثلاً در صفحۀ تنظیمات، دربارۀ و ...
</div>

**Comment by neesti** [comment]
<div dir=rtl>
آهان، ببخشید. 
نه، بقیهٔ جاهای واژه‌یار چنین مشکلی ندارند!

**Comment by kokabi1365** [comment]
<div dir="rtl">
من در ویندوز 10 با رزولوشن شما همچنان مشکلی برای آیکون‌ها نمی‌بینم. پیدا کردن منشاء مشکلاتی که برای توسعه‌دهنده به وجود نمیاد اندکی زمانبره. لطفاً ایملتون رو بدید تا در فرایند تست از شما کمک بگیرم.  
</div>

**Comment by kokabi1365** [comment]
Fix #5

**Comment by kokabi1365** [comment]
<div dir="rtl">
مشکل حل شد.
</div>
