### ISSUE TITLE
نوار پیمایشگر

### ISSUE THREAD

**Issue by neesti** [kokabi1365/Vajehyar#6]
<div dir=rtl>
به‌نظرتان اگر نوار پیمایشگرِ (Scroll Bar) معانی در سمت راست پنجرهٔ برنامه باشد بهتر و فارسی‌پسندتر نیست؟

**Comment by kokabi1365** [comment]
<div dir="rtl">
این کار طبق استانداردهای زبان‌های راست به چپ انجام شده؛ اما فکر نمی‌کنم تغییر مکان اسکرول به راست مشکلی برای کاربر ایجاد کنه. در نسخۀ بعدی تغییرش میدم به راست.
</div>
