### ISSUE TITLE
عددِ معانی

### ISSUE THREAD

**Issue by neesti** [kokabi1365/Vajehyar#7]
<div dir=rtl>
پیشنهاد می‌کنم عددِ معانی هر کلمه را یا داخل پرانتز بگذارید یا یک نقطه بعدش بگذارید تا با معانی کلماتِ بعدی و قبلی قاتی نشود!

**Comment by kokabi1365** [comment]
<div dir="rtl">
اون اعداد در خودِ دیتابیس برنامه هست که متأسفانه چون به هم‌ریخته است هنوز وقت نکردم بهش دست بزنم. سعی می‌کنم در نسخۀ بعدی نتایج رو زیباتر نشون بدم.
</div>

**Comment by zoghal** [comment]
درود و عرض خسته نباشید
و تشکر ویژه
تو دیتابیس یک سری کلمات یک عدد دارند:

> ابتکار، 1 ابداع، اختراع، بدعت، نوآوری 2 ذوق، قریحه 3 پگاه‌خیزی، سحرخیزی

دقیقا این اعداد چی هستند میشه یک راهنمایی کنید؟!

**Comment by kokabi1365** [comment]
<div dir="rtl">
ممنون. سلامت باشید. 
اون اعداد بیانگر حوزه‌های معنایی است. یعنی مترادف **ابتکار** در سه حوزۀ معنایی تعریف شده: 
1. ابداع، اختراع، بدعت، نوآوری؛
2.  ذوق، قریحه؛
3.  پگاه‌خیزی و سحرخیزی.
حالا شما در هر حوزۀ معنایی که مدنظر دارید به جستجوی مترادف دلخواه می‌پردازید. اینطوری دیگه نیازی به بررسی سایر قسمت‌ها نیست. طبقه‌بندی کلمات را نویسنده بر اساس اصول زبان‌شناسی و مطابق فرهنگ‌های فارسی دیگر انجام داده است. ان‌شاء الله در نسخه‌های بعدی این حوزه‌های معنایی به صورت گرافیکی و جدا از هم نشان داده خواهند شد.
</div>

**Comment by zoghal** [comment]
ممنون از توضیحات، این حوزه‌های معانی دقیقا بر چه اساسی هستند.
راستش من شدیدا دنبال این هستم که بدونم یک واژه فارسی دقیقا شامل چه خصوصیاتی می‌شود. آیا منبعی برای یادگیری این موضوع دارید به من بدهید؟

**Comment by kokabi1365** [comment]
<div dir="rtl">
متأسفانه در این زمینه چندان اطلاعات ندارم. پیشنهاد می‌کنم از افراد آگاه‌تری مثل محمد یوسفی و محمد مهدی باقری بپرسید. آیدی تلگرام اولی: Myoosofi و دومی Bagheri
</div>
